init_data: [1501, 2,14,  26,  0.6136,  2,  3]
filter_threshold: -1
target_number: 50
datasets:
  path: "data/new.xlsx"
  sence_columns: ["降雨量/mm", "坡度/°", "土壤氮含量（g/kg）", "氮肥利用效率%", "NDVI(植被覆盖)", "植被类型", "土地利用类型"]
  process_columns: ["用量（株/平方米）", "氮肥施肥量（kg/亩)", "磷肥施肥量（kg/亩)"]
  type_columns: ["技术分类"]
  result_columns: ["入水口水中氮含量降低程度（%）"]
