init_data: [0.5, 0.5, 0.5, 0.5, 0.5]
filter_threshold: 0.6
datasets:
  path: "data/决策算法测试数据.xlsx"
  sence_columns: ["Cdtotal", "CECsoil", "ECsoil", "pHsoil", "SOM"]
  process_columns: ["TPV", "DosageBC", "Time"]
  type_columns: ["Type"]
  result_columns: ["Cdreduction rate"]
train:
  test_size: 0.2
  random_state: 42

# search_parameters 相关超参数
search_parameters:
  threshold: 10          # 阈值参数（原 search_params_threshold）
  num_iter: 4            # 迭代次数（原 search_params_num_iter）
  multiplier: 0.95       # 目标值乘数
  num_candidates_per_round: 5               # 每轮选择的最优参数数量

select_variables_threshold: 0.5
select_variables_max_num: 5
